name: copy_with_isar
description: Small lib for add annotations to isar models.
repository: "https://github.com/n0vit/copy_with_isar"
version: 0.0.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  build: ^2.4.1
  source_gen: ^1.5.0
  analyzer: ^5.13.0

dev_dependencies:
  build_runner: ^2.4.9
  lints: ^3.0.0
  test: ^1.24.0
  build_test: ^2.0.0
